# flask-app-servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app-monitor
  namespace: monitoring # Must be in the same namespace as Prometheus
  labels:
    release: prometheus-stack # Must match the label used by the Prometheus component (set by the helm chart)
spec:
  selector:
    matchLabels:
      app: flask-app # Matches the selector label defined in your Flask App Service
  endpoints:
    - port: http # Refers to the name of the port defined in the Flask App Service
      path: /metrics # The endpoint your Flask application exposes (from Step 1)
      interval: 15s # How frequently Prometheus should scrape
  namespaceSelector:
    matchNames:
      - monitoring# Tells the ServiceMonitor to look for Services in the 'monitoring' namespace (where your app is)
